spring:
  application.name : api-gateway
  cloud:
    gateway:
      routes:
        - id : product-service
          uri : http://localhost:8082
          predicates:
            - Path=/api/product/**
        - id : order-service
          uri : http://localhost:8083
          predicates :
            - Path=/api/order/**
        - id : discovery-service
          uri : http://localhost:8761
          predicates :
            - Path=/eureka/web
          filters :
            - SetPath=/
        - id: discovery-service-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
        - id: inventory-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/inventory/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server.port : 8080

logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway:
            route:
              - RouteDefinitionRouteLocator: info
              - Trace