spring:
    application.name : order-service
    r2dbc:
        username: ${database.user}
        password: ${database.password}
        url: r2dbc:${database.url}
    flyway:
        user: ${database.user}
        password: ${database.password}
        url: jdbc:${database.url}
        baselineOnMigrate: true
        table: flyway_order_schema_history

database:
    url: postgresql://localhost:5432/shopping_optimization
    user: elifarikan
    password: db_pass

server.port : 8083
