spring:
  application.name : product-service
  r2dbc:
    username: ${database.user}
    password: ${database.password}
    url: r2dbc:${database.url}
  flyway:
    user: ${database.user}
    password: ${database.password}
    url: jdbc:${database.url}
    baselineOnMigrate: true
    table: flyway_product_schema_history

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
database:
  url: postgresql://horton.db.elephantsql.com/qddaimwj
  user: qddaimwj
  password: aKYmIOp789I16fnvoSEY79iY9Bbc0qDt

server.port : 8082